"""phase15_new_location_fields

Revision ID: 23ec75c72ce6
Revises: dbb2fd2ff92b
Create Date: 2026-09-22 16:43:14.572671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ec75c72ce6'
down_revision: Union[str, Sequence[str], None] = 'dbb2fd2ff92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('census_code', sa.Integer(), nullable=True))
    op.add_column('blocks', sa.Column('status', sa.String(), nullable=True))
    op.add_column('blocks', sa.Column('source', sa.String(), nullable=True))
    op.add_column('blocks', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('blocks', sa.Column('source_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_blocks_district_id'), 'blocks', ['district_id'], unique=False)
    op.add_column('districts', sa.Column('census_code', sa.Integer(), nullable=True))
    op.add_column('districts', sa.Column('status', sa.String(), nullable=True))
    op.add_column('districts', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('districts', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('districts', sa.Column('geometry_source', sa.String(), nullable=True))
    op.add_column('districts', sa.Column('panchayat_count', sa.Integer(), nullable=True))
    op.add_column('districts', sa.Column('weather_coverage_pct', sa.Float(), nullable=True))
    op.add_column('districts', sa.Column('source', sa.String(), nullable=True))
    op.add_column('districts', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('districts', sa.Column('source_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.add_column('panchayats', sa.Column('census_code', sa.Integer(), nullable=True))
    op.add_column('panchayats', sa.Column('status', sa.String(), nullable=True))
    op.add_column('panchayats', sa.Column('geometry_status', sa.String(), nullable=True))
    op.add_column('panchayats', sa.Column('geocoding_matched_name', sa.String(), nullable=True))
    op.add_column('panchayats', sa.Column('geocoding_query', sa.String(), nullable=True))
    op.add_column('panchayats', sa.Column('geocoding_confidence', sa.Float(), nullable=True))
    op.add_column('panchayats', sa.Column('geocoding_retrieved_at', sa.DateTime(), nullable=True))
    op.add_column('panchayats', sa.Column('weather_available', sa.Boolean(), nullable=True))
    op.add_column('panchayats', sa.Column('weather_status', sa.String(), nullable=True))
    op.add_column('panchayats', sa.Column('elevation_m', sa.Float(), nullable=True))
    op.add_column('panchayats', sa.Column('elevation_source', sa.String(), nullable=True))
    op.add_column('panchayats', sa.Column('elevation_retrieved_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_panchayats_block_id'), 'panchayats', ['block_id'], unique=False)
    op.add_column('states', sa.Column('census_code', sa.Integer(), nullable=True))
    op.add_column('states', sa.Column('status', sa.String(), nullable=True))
    op.add_column('states', sa.Column('source', sa.String(), nullable=True))
    op.add_column('states', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('states', sa.Column('source_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'source_updated_at')
    op.drop_column('states', 'source_url')
    op.drop_column('states', 'source')
    op.drop_column('states', 'status')
    op.drop_column('states', 'census_code')
    op.drop_index(op.f('ix_panchayats_block_id'), table_name='panchayats')
    op.drop_column('panchayats', 'elevation_retrieved_at')
    op.drop_column('panchayats', 'elevation_source')
    op.drop_column('panchayats', 'elevation_m')
    op.drop_column('panchayats', 'weather_status')
    op.drop_column('panchayats', 'weather_available')
    op.drop_column('panchayats', 'geocoding_retrieved_at')
    op.drop_column('panchayats', 'geocoding_confidence')
    op.drop_column('panchayats', 'geocoding_query')
    op.drop_column('panchayats', 'geocoding_matched_name')
    op.drop_column('panchayats', 'geometry_status')
    op.drop_column('panchayats', 'status')
    op.drop_column('panchayats', 'census_code')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_column('districts', 'source_updated_at')
    op.drop_column('districts', 'source_url')
    op.drop_column('districts', 'source')
    op.drop_column('districts', 'weather_coverage_pct')
    op.drop_column('districts', 'panchayat_count')
    op.drop_column('districts', 'geometry_source')
    op.drop_column('districts', 'lon')
    op.drop_column('districts', 'lat')
    op.drop_column('districts', 'status')
    op.drop_column('districts', 'census_code')
    op.drop_index(op.f('ix_blocks_district_id'), table_name='blocks')
    op.drop_column('blocks', 'source_updated_at')
    op.drop_column('blocks', 'source_url')
    op.drop_column('blocks', 'source')
    op.drop_column('blocks', 'status')
    op.drop_column('blocks', 'census_code')
    # ### end Alembic commands ###
