"""Add is_test_data to Panchayat

Revision ID: ac40a865e3ea
Revises: 9a97200349a5
Create Date: 2026-09-20 15:07:16.332488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac40a865e3ea'
down_revision: Union[str, Sequence[str], None] = '9a97200349a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panchayats', sa.Column('is_test_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panchayats', 'is_test_data')
    # ### end Alembic commands ###
