"""Init

Revision ID: afc5b344b468
Revises: 
Create Date: 2026-09-19 15:12:03.979464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afc5b344b468'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_sources_id'), 'forecast_sources', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_sources_name'), 'forecast_sources', ['name'], unique=True)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=True)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_id'), 'blocks', ['id'], unique=False)
    op.create_index(op.f('ix_blocks_name'), 'blocks', ['name'], unique=False)
    op.create_table('panchayats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panchayats_id'), 'panchayats', ['id'], unique=False)
    op.create_index(op.f('ix_panchayats_name'), 'panchayats', ['name'], unique=False)
    op.create_table('advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panchayat_id', sa.Integer(), nullable=True),
    sa.Column('generated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisories_generated_time'), 'advisories', ['generated_time'], unique=False)
    op.create_index(op.f('ix_advisories_id'), 'advisories', ['id'], unique=False)
    op.create_index(op.f('ix_advisories_valid_from'), 'advisories', ['valid_from'], unique=False)
    op.create_index(op.f('ix_advisories_valid_to'), 'advisories', ['valid_to'], unique=False)
    op.create_table('forecast_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('panchayat_id', sa.Integer(), nullable=True),
    sa.Column('issue_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['forecast_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_records_id'), 'forecast_records', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_records_issue_time'), 'forecast_records', ['issue_time'], unique=False)
    op.create_index(op.f('ix_forecast_records_valid_time'), 'forecast_records', ['valid_time'], unique=False)
    op.create_table('localized_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panchayat_id', sa.Integer(), nullable=True),
    sa.Column('valid_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('variable', sa.String(), nullable=True),
    sa.Column('reference_value', sa.Float(), nullable=True),
    sa.Column('localized_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('method_id', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('reliability_status', sa.String(), nullable=True),
    sa.Column('uncertainty_min', sa.Float(), nullable=True),
    sa.Column('uncertainty_max', sa.Float(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=True),
    sa.Column('fallback_reason', sa.String(), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localized_forecasts_id'), 'localized_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_localized_forecasts_valid_time'), 'localized_forecasts', ['valid_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_localized_forecasts_valid_time'), table_name='localized_forecasts')
    op.drop_index(op.f('ix_localized_forecasts_id'), table_name='localized_forecasts')
    op.drop_table('localized_forecasts')
    op.drop_index(op.f('ix_forecast_records_valid_time'), table_name='forecast_records')
    op.drop_index(op.f('ix_forecast_records_issue_time'), table_name='forecast_records')
    op.drop_index(op.f('ix_forecast_records_id'), table_name='forecast_records')
    op.drop_table('forecast_records')
    op.drop_index(op.f('ix_advisories_valid_to'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_valid_from'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_id'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_generated_time'), table_name='advisories')
    op.drop_table('advisories')
    op.drop_index(op.f('ix_panchayats_name'), table_name='panchayats')
    op.drop_index(op.f('ix_panchayats_id'), table_name='panchayats')
    op.drop_table('panchayats')
    op.drop_index(op.f('ix_blocks_name'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_forecast_sources_name'), table_name='forecast_sources')
    op.drop_index(op.f('ix_forecast_sources_id'), table_name='forecast_sources')
    op.drop_table('forecast_sources')
    # ### end Alembic commands ###
