"""Add LGD fields and provenance to geographic models

Revision ID: dbb2fd2ff92b
Revises: ac40a865e3ea
Create Date: 2026-09-21 16:37:08.194993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb2fd2ff92b'
down_revision: Union[str, Sequence[str], None] = 'ac40a865e3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('lgd_code', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_blocks_lgd_code'), 'blocks', ['lgd_code'], unique=True)
    op.add_column('districts', sa.Column('lgd_code', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_districts_lgd_code'), 'districts', ['lgd_code'], unique=True)
    op.add_column('panchayats', sa.Column('lgd_code', sa.Integer(), nullable=True))
    op.add_column('panchayats', sa.Column('local_body_type', sa.String(), nullable=True))
    op.add_column('panchayats', sa.Column('geometry_source', sa.String(), nullable=True))
    op.add_column('panchayats', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('panchayats', sa.Column('source_updated_at', sa.DateTime(), nullable=True))
    op.add_column('panchayats', sa.Column('data_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_panchayats_lgd_code'), 'panchayats', ['lgd_code'], unique=True)
    op.add_column('states', sa.Column('lgd_code', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_states_lgd_code'), 'states', ['lgd_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_states_lgd_code'), table_name='states')
    op.drop_column('states', 'lgd_code')
    op.drop_index(op.f('ix_panchayats_lgd_code'), table_name='panchayats')
    op.drop_column('panchayats', 'data_status')
    op.drop_column('panchayats', 'source_updated_at')
    op.drop_column('panchayats', 'source_url')
    op.drop_column('panchayats', 'geometry_source')
    op.drop_column('panchayats', 'local_body_type')
    op.drop_column('panchayats', 'lgd_code')
    op.drop_index(op.f('ix_districts_lgd_code'), table_name='districts')
    op.drop_column('districts', 'lgd_code')
    op.drop_index(op.f('ix_blocks_lgd_code'), table_name='blocks')
    op.drop_column('blocks', 'lgd_code')
    # ### end Alembic commands ###
