"""National Migration Model Refactoring

Revision ID: f61b7ae2d551
Revises: 23ec75c72ce6
Create Date: 2026-09-23 17:11:21.890697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61b7ae2d551'
down_revision: Union[str, Sequence[str], None] = '23ec75c72ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panchayats', sa.Column('gpc_code', sa.Integer(), nullable=True))
    op.add_column('panchayats', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('panchayats', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('panchayats', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('panchayats', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('panchayats', sa.Column('coordinate_source', sa.String(), nullable=True))
    op.create_index(op.f('ix_panchayats_district_id'), 'panchayats', ['district_id'], unique=False)
    op.create_index(op.f('ix_panchayats_gpc_code'), 'panchayats', ['gpc_code'], unique=True)
    op.create_index(op.f('ix_panchayats_state_id'), 'panchayats', ['state_id'], unique=False)
    op.create_foreign_key(None, 'panchayats', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(None, 'panchayats', 'states', ['state_id'], ['id'])
    op.drop_column('panchayats', 'lat')
    op.drop_column('panchayats', 'lon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panchayats', sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('panchayats', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'panchayats', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'panchayats', type_='foreignkey')
    op.drop_index(op.f('ix_panchayats_state_id'), table_name='panchayats')
    op.drop_index(op.f('ix_panchayats_gpc_code'), table_name='panchayats')
    op.drop_index(op.f('ix_panchayats_district_id'), table_name='panchayats')
    op.drop_column('panchayats', 'coordinate_source')
    op.drop_column('panchayats', 'longitude')
    op.drop_column('panchayats', 'latitude')
    op.drop_column('panchayats', 'district_id')
    op.drop_column('panchayats', 'state_id')
    op.drop_column('panchayats', 'gpc_code')
    # ### end Alembic commands ###
